### ISSUE TITLE
[REFACTOR] - Use Case로 잘못 들어간 코드 `ViewModel` 로 분리

### ISSUE THREAD

**Issue by junbangg** [junbangg/yogiyo#11]
# Issue
- `Repository` 로부터 받아오느 데이터를 `Use Case` 가 정제한 후에 `ViewModel` 로 넘겨주는데, 이때 넘겨주는 형태가 `TableView` 에 보여질 데이터의 형태라는게 클린 아키텍쳐와 맞지 않다.
- `View` 에 보여줄 형태로 만드는 것은 `ViewModel` 에서 하는 것이 올바르다고 판단해서 리팩토링 결정.

# TODO
- [x] 해당 코드를 `ViewModel` 로 옮기기
- [x] `RxDataSources` 형태의 타입을 `ViewModel` 에서 만들기
- [x] `RxDataSources` 이전 형태의 타입을 만들어서 `Domain` 타입으로 사용
