### ISSUE TITLE
[DOCUMENTATION] - README 수정사항

### ISSUE THREAD

**Issue by junbangg** [junbangg/yogiyo#13]
# TODO
- [ ] 클린 아키텍쳐 그림에 있는 의존성 방향 수정
- [ ] Use Case < - > Data 간의 의존성 역전 리팩토링 문서화
- [ ] Domain 데이터와 DTO 데이터 분리한 리팩토링 문서화
